export const LABELS = {
    wellcomeBack: 'Welcome Back!',
    signInToContinue: 'Sign in to continue',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    signInButton: 'Sign In',
    dontHaveAccount: "Don't have an account? ",
    signUpHere: 'Sign Up',
    signInFailed: 'Sign in failed.',
    anError: 'An error occurred. Please try again.',
    biometricAuthFailed: 'Biometric authentication failed. Please try again.',
    noStoredCredentials: 'No stored credentials found. Please sign in manually.',  
    emailRequired: 'Email is required.',
    passwordRequired: 'Password is required.',
    faceId: 'Sign in with Face ID',
    touchId: 'Sign in with Touch ID',
    biometric: 'Sign in with Biometrics',
    invalidEmailAddress: 'Invalid email address.',
    passwordMinLength: 'Password must be at least 6 characters.',
};