export const LABELS = {
  today: 'Today',
  quickActions: 'Quick Actions',
  upcomingEvents: 'Upcoming Events',
  noUpcomingEvents: 'No upcoming events',
  addFirstEvent: 'Add your first event to get started',
  calendar: 'Calendar',
  createEvent: 'Create a new calendar event',
  neverMissDates: 'Never miss important dates',
  setReminder: 'Set Reminder',
  viewFullSchedule: 'See your full schedule',
  viewAllEvents: 'View All Events',
  eventsOn: 'Events on',
  firstEventPrompt: 'Add your first event to get started',
  month: 'Month',
  week: 'Week',
  day: 'Day',
  addEvent: 'Add Event',
  editEvent: 'Edit Event',
};