export const LABELS = {
  addEvent: 'Add Event',
  editEvent: 'Edit Event',
  close: '✕',
  titleLabel: 'Title *',
  titlePlaceholder: 'Event title',
  dateLabel: 'Date',
  timeLabel: 'Time',
  timePlaceholder: 'HH:MM',
  notificationLabel: 'Notification',
  notificationSubtext: 'Get notified at event time',
  buttonCancel: 'Cancel',
  buttonSave: 'Save',
  buttonUpdate: 'Update',
  buttonDelete: 'Delete',
  errorTitleRequired: 'Title is required',
  errorTitleMinLength: 'Title must be at least 3 characters',
  errorTimeRequired: 'Time is required',
  errorTimeFormat: 'Invalid time format (HH:MM)',
  alertDeleteTitle: 'Delete Event',
  alertDeleteMessage: 'Are you sure you want to delete this event?',
  alertCancel: 'Cancel',
  alertDelete: 'Delete',
};
